### ISSUE TITLE
OpenGL and Vulkan

### ISSUE THREAD

**Issue by ShalokShalom** [jmquigs/ModelMod#15]
Well, since a huge number of game developers prefer to work on macOS and some specific people are interested in a Linux version (me ;D) - is this here the official issue about the implementation of OpenGL.

**Comment by jmquigs** [comment]
For Linux, its possible it might work under Wine already (the DLL injection might cause issues.  I did not really do that properly and need to rewrite it to use a more standard method).  

For 3D renderers, the most important is 64-bit D3D11 since that opens up a significant number of more recent games.  

Anyway this project is not a priority for me at this time.  If I do anything in the near future, it will be fix the DLL injection on windows.  I welcome PRs though :)
