### ISSUE TITLE
Suggestion: automatic mod to disable legendary trinket effects in GW2

### ISSUE THREAD

**Issue by Kidel** [jmquigs/ModelMod#21]
Hi. First of all thanks for your tool. 

As you may be aware, the most requested thing on the GW2 forums is an option to disable legendary trinket effects. Anet is not against it but they say it's too difficult to do (lol). 

Since you already showed how yo disable the Aegis effect, I'm sure it would be possible to also disable the legendary trinket effect (that they claim to be based on a boon too).

I'm pretty sure most people would gladly download the pre-made mod and this would also probably raise awareness on the subject.

**Comment by Kidel** [comment]
uhm it's not that simple. The preview doesn't show those effects. 

Basically if you equip a legendary trinket you get a hidden boon and balls start floating around your character. Some legendary trinkets have a static effect (the bubble is always the same), other ones have a **"stacking"** effect, meaning that if you equip 1 (regardless of which one) you get some floaty balls, if you equip 2 you get some different floaty balls, if you equip 3 you get different floaty balls and a hge black one in the middle. 

The best way to see that effect is to have a character or a friend that has all the legendary trinkets and get the 5 different effects. Or get a friend who has the 3 stacking ones and another who has the 2 non stacking ones.

**Comment by jmquigs** [comment]
If that is what it takes to repro, it's going to make it very hard to test any kind of fix.  When developing something new like this I usually need to iterate a dozen or more times.  I don't think I'll be able to work on this, sorry.  

From your description I still think reshade is the best bet.  Basically modify the shaders to do some kind of pass-through.  For the balls it could output completely transparent pixels so that they are hidden.  Shaders are not my area of expertise so I don't know how difficult this will be in practice.
