### ISSUE TITLE
This is not an issue, its a thank you

### ISSUE THREAD

**Issue by ImaUnknownDev** [jmquigs/ModelMod#22]
Hi mate, didn't know which way to reach you, so I'm doing this here, just wanted to say thank you, Either it's for GW1 or GW2, your tool works like a charm. I absolutely love it! I was able to do some stuff I didn't know would of been possible! 
Here's a link to my reddit post, if you'd like to, I can give you credit for your tool , just wanted to ask before. 
Here's what I made, hope you'll like the result

Thanks again bud, keep updating MM please, it's a masterpiece!

https://www.reddit.com/r/GuildWars/comments/pewpkx/fow_ra_armor/

**Comment by jmquigs** [comment]
Nice work!  I still use it for GW1 sometimes, though, I don't game that much anymore.

Sure you can mention MM on your post.  I doubt ANet would freak out over GW1 much at this point, since its very old and there are other kinds of tools messing with it, like the Toolbox. 

Sadly I don't have my tutorial videos anymore.  So you might need to help people learn how to use it if they are interested.  The trick in GW1, of course, is to use the right set of glove armor so that it forces GPU animation, which is required for MM.   There is a plugin for Toolbox/GWCA, the Armory, which lets you preview different armor types and then you can try snapshotting them to see if they will work.  I don't know if they distribute that officially.  I had to hack together a custom build of their stuff to get it working.

**Comment by ImaUnknownDev** [comment]
@jmquigs , thank you very much mate ! Might have a question, do you know how to script a .yaml in order that it just replace texture and doesn't ask for an external mesh ( .mmobj) ; The thing is that if I export the armor icons, it export the mesh aswell, since it's a ui , it messed up the whole ui since it requires the external .mmobj to be present. Any idea how i could script the .yaml in order to skip the mesh search ? thank you

**Comment by jmquigs** [comment]
@ImaUnknownDev, unfortunately you can't mod the UI like that.  MM doesn't work like texmod, it can't just replace single textures.  That is because it replaces based on geometry (primitive and vertex count) and not based on texture checksums.  So what is happening in your case is that MM is replacing every quad on the screen (2 primitives, 4 verts).

I have considered adding this feature to MM but it would require checksumming every texture loaded by the game, just like I presume TexMod is doing, which is fair amount of work and not something I have needed.  Also of course, texmod is pretty slick for what it does and I won't be able to reimplement all of its features.

**Comment by ImaUnknownDev** [comment]
Alright thanks for your answer! Other than that might have another question, saw that it was possible to weight the armor/body , didn't found how... How should I proceed in order to custom weight the armor pieces/body? 
Thanks again for your time !

**Comment by ImaUnknownDev** [comment]
btw, made a tutorial for people to understand your tool and modelmod their GW, -> https://www.youtube.com/watch?v=Mfpd3FlWeXE&t=120s&ab_channel=ImaUnknownDev

If i missed anything let me know
