### ISSUE TITLE
Anti-cheat workaround?

### ISSUE THREAD

**Issue by RenegadeWraith** [jmquigs/ModelMod#27]
Many games have anticheat which detect d3d9.dll and this makes the mod unusable. Is there any way to work around this?

To add some more info: The anticheat is simply looking through the game folder and sees d3d9.dll which shouldn't be there. If there was a more global injection method, this would perhaps be better.

**Comment by jmquigs** [comment]
I used to use a global injector (along the lines of what the old oblivion script extender did) but it was unreliable and didn't work for a lot of people.  This can be done as a separate app, what you have to do is start the target game and immediately suspend it, then hook its load library function so that MM's d3d9 gets loaded.  The old code that did that is here: https://github.com/jmquigs/ModelMod/tree/e99016a75405066bcb0f4d813a05ff180c213013/MMLoader.  Some of the old modelmod releases contain a prebuilt executable for that but I don't recall which versions, or if it hardcoded the dll it used.

I doubt I will bring this back personally however
